# ============================================================
# 56b — JAK3 SUPERVISOR-FACING PRIORITY HEATMAP
#
# Uses the ranking generated by script 56.
# Does NOT alter the ranking score.
#
# Heatmap explicitly shows:
# 1. Tumor-vs-normal upregulation
# 2. Stage-I-vs-normal upregulation
# 3. Persistence after PTPRC adjustment
# 4. Persistence after 10-marker ImmuneScore adjustment
# 5. Leukocyte-fraction correlation as contextual information
# 6. Final descriptive priority score
#
# *  = passes all conservative core criteria
# †  = small normal cohort
# ============================================================

rm(list = ls())
options(stringsAsFactors = FALSE)

suppressPackageStartupMessages(
  library(ggplot2)
)

indir <-
  "TCGA_JAK3_pan_cancer/results/release"

figdir <-
  "TCGA_JAK3_pan_cancer/figures/final"

dir.create(
  figdir,
  recursive = TRUE,
  showWarnings = FALSE
)

# ------------------------------------------------------------
# Read ranking and availability/sample-size information
# ------------------------------------------------------------

rank <- read.csv(
  file.path(
    indir,
    "JAK3_tumor_priority_ranking.csv"
  ),
  stringsAsFactors = FALSE,
  check.names = FALSE
)

avail <- read.csv(
  file.path(
    indir,
    "JAK3_complete_33cancer_analysis_availability.csv"
  ),
  stringsAsFactors = FALSE,
  check.names = FALSE
)

# ------------------------------------------------------------
# Merge sample-size information
# ------------------------------------------------------------

keep_avail <- avail[
  ,
  c(
    "project",
    "Normal_patients",
    "Stage_I_patients",
    "Small_normal_n",
    "Small_stageI_n"
  )
]

dat <- merge(
  rank,
  keep_avail,
  by = "project",
  all.x = TRUE,
  sort = FALSE
)

# Restore ranking order after merge
dat <- dat[
  order(dat$Priority_rank),
]

# ------------------------------------------------------------
# Display labels
#
# *  = strict core candidate
# †  = small normal cohort
# ------------------------------------------------------------

dat$core_mark <- ifelse(
  dat$Core_candidate %in% TRUE,
  " *",
  ""
)

dat$small_normal_mark <- ifelse(
  dat$Small_normal_n %in% TRUE,
  " \u2020",
  ""
)

dat$Cancer_display <- paste0(
  dat$Cancer,
  dat$core_mark,
  dat$small_normal_mark,
  "   (N=",
  dat$Normal_patients,
  "; Stage-I=",
  dat$Stage_I_patients,
  ")"
)

dat$Cancer_display <- factor(
  dat$Cancer_display,
  levels = rev(dat$Cancer_display)
)

# ------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------

yes_no <- function(x) {

  ifelse(
    is.na(x),
    "NA",
    ifelse(
      x,
      "Yes",
      "No"
    )
  )
}

binary_fill <- function(x) {

  ifelse(
    is.na(x),
    NA_real_,
    ifelse(
      x,
      1,
      0
    )
  )
}

# ------------------------------------------------------------
# Leukocyte-fraction context
#
# Low |rho| is displayed as stronger support that the overall
# bulk signal is less tightly coupled to leukocyte abundance.
#
# IMPORTANT:
# This value is shown as context only and is NOT included
# in the Priority_score.
# ------------------------------------------------------------

dat$Low_leukocyte_coupling <- ifelse(
  is.na(dat$LF_Spearman_rho),
  NA_real_,
  1 - pmin(
    abs(dat$LF_Spearman_rho),
    1
  )
)

# ------------------------------------------------------------
# Construct heatmap matrix
# ------------------------------------------------------------

heat <- rbind(

  data.frame(
    Cancer = dat$Cancer_display,
    Feature = "Tumor-normal\nUP",
    Fill = dat$Tumor_UP_strength,
    Label = sprintf(
      "\u0394 %.2f",
      dat$TN_median_log2TPM1_difference
    )
  ),

  data.frame(
    Cancer = dat$Cancer_display,
    Feature = "Stage-I-normal\nUP",
    Fill = dat$Early_UP_strength,
    Label = sprintf(
      "\u0394 %.2f",
      dat$StageI_median_log2TPM1_difference
    )
  ),

  data.frame(
    Cancer = dat$Cancer_display,
    Feature = "TN after\nPTPRC",
    Fill = binary_fill(
      dat$TN_positive_persists_after_PTPRC
    ),
    Label = yes_no(
      dat$TN_positive_persists_after_PTPRC
    )
  ),

  data.frame(
    Cancer = dat$Cancer_display,
    Feature = "TN after\nImmuneScore",
    Fill = binary_fill(
      dat$TN_positive_persists_after_ImmuneScore
    ),
    Label = yes_no(
      dat$TN_positive_persists_after_ImmuneScore
    )
  ),

  data.frame(
    Cancer = dat$Cancer_display,
    Feature = "Stage-I after\nPTPRC",
    Fill = binary_fill(
      dat$StageI_positive_persists_after_PTPRC
    ),
    Label = yes_no(
      dat$StageI_positive_persists_after_PTPRC
    )
  ),

  data.frame(
    Cancer = dat$Cancer_display,
    Feature = "Stage-I after\nImmuneScore",
    Fill = binary_fill(
      dat$StageI_positive_persists_after_ImmuneScore
    ),
    Label = yes_no(
      dat$StageI_positive_persists_after_ImmuneScore
    )
  ),

  data.frame(
    Cancer = dat$Cancer_display,
    Feature = "Low leukocyte\ncoupling",
    Fill = dat$Low_leukocyte_coupling,
    Label = ifelse(
      is.na(dat$LF_Spearman_rho),
      "NA",
      sprintf(
        "\u03c1 %.2f",
        dat$LF_Spearman_rho
      )
    )
  ),

  data.frame(
    Cancer = dat$Cancer_display,
    Feature = "Priority\nscore",
    Fill = dat$Priority_score / 100,
    Label = sprintf(
      "%.1f",
      dat$Priority_score
    )
  )
)

# ------------------------------------------------------------
# Explicit column order
# ------------------------------------------------------------

heat$Feature <- factor(
  heat$Feature,
  levels = c(
    "Tumor-normal\nUP",
    "Stage-I-normal\nUP",
    "TN after\nPTPRC",
    "TN after\nImmuneScore",
    "Stage-I after\nPTPRC",
    "Stage-I after\nImmuneScore",
    "Low leukocyte\ncoupling",
    "Priority\nscore"
  )
)

# ------------------------------------------------------------
# Final heatmap
# ------------------------------------------------------------

p <- ggplot(
  heat,
  aes(
    x = Feature,
    y = Cancer,
    fill = Fill
  )
) +
  geom_tile(
    linewidth = 0.55
  ) +
  geom_text(
    aes(
      label = Label
    ),
    size = 3.1
  ) +
  scale_fill_gradient(
    limits = c(0, 1),
    name = "Relative\nsupport"
  ) +
  labs(
    title =
      "JAK3 TCGA tumor prioritization",
    subtitle =
      "Strong upregulation, early-stage elevation, and persistence after immune adjustment",
    x = NULL,
    y = NULL,
    caption = paste0(
      "* passes all conservative core criteria; ",
      "\u2020 small normal cohort. ",
      "N = normal patients; Stage-I = Stage-I tumor patients. ",
      "Leukocyte \u03c1 is contextual and is not included in the priority score."
    )
  ) +
  theme_minimal(
    base_size = 11
  ) +
  theme(
    panel.grid = element_blank(),

    plot.title = element_text(
      face = "bold",
      size = 15
    ),

    plot.subtitle = element_text(
      size = 11
    ),

    axis.text.y = element_text(
      size = 9
    ),

    axis.text.x = element_text(
      size = 9,
      face = "bold"
    ),

    plot.caption = element_text(
      hjust = 0,
      size = 8.5
    ),

    legend.position = "right"
  )

# ------------------------------------------------------------
# Save final supervisor-facing heatmap
# ------------------------------------------------------------

ggsave(
  file.path(
    figdir,
    "Figure_8_JAK3_priority_heatmap.png"
  ),
  p,
  width = 13,
  height = 8.5,
  dpi = 320
)

ggsave(
  file.path(
    figdir,
    "Figure_8_JAK3_priority_heatmap.pdf"
  ),
  p,
  width = 13,
  height = 8.5
)

# ------------------------------------------------------------
# Console audit
# ------------------------------------------------------------

cat("\n========================================\n")
cat("56b SUPERVISOR PRIORITY HEATMAP\n")
cat("========================================\n\n")

cat(
  "Cancers displayed:",
  nrow(dat),
  "\n"
)

cat(
  "Core candidates:",
  sum(dat$Core_candidate %in% TRUE),
  "\n"
)

cat(
  "Small-normal cohorts:",
  sum(dat$Small_normal_n %in% TRUE),
  "\n\n"
)

cat("Top 10 display order:\n\n")

print(
  dat[
    seq_len(
      min(
        10,
        nrow(dat)
      )
    ),
    c(
      "Priority_rank",
      "Cancer",
      "Normal_patients",
      "Stage_I_patients",
      "Small_normal_n",
      "Priority_score",
      "LF_Spearman_rho",
      "Core_candidate"
    )
  ],
  row.names = FALSE
)

cat("\nSaved:\n")
cat(
  " ",
  file.path(
    figdir,
    "Figure_8_JAK3_priority_heatmap.png"
  ),
  "\n"
)

cat(
  " ",
  file.path(
    figdir,
    "Figure_8_JAK3_priority_heatmap.pdf"
  ),
  "\n"
)

cat("\n========================================\n")
cat("56b COMPLETE\n")
cat("========================================\n")
