# ============================================================
# 12o — Correct final sections of analysis_report.Rmd
# ============================================================

rm(list = ls())

file <- "analysis_report.Rmd"

if (!file.exists(file)) {
  stop("analysis_report.Rmd not found")
}

x <- readLines(file, warn = FALSE, encoding = "UTF-8")

start <- grep("^# 16\\. Limitations$", x)

if (length(start) != 1) {
  stop("Could not uniquely locate '# 16. Limitations'")
}

new_tail <- c(

"# 16. Limitations",
"",
"The main limitations are:",
"",
"1. **Day-1 RNA sample size:** only two matched pairs were available, limiting FDR power for the acute-response analysis.",
"2. **β-glucan rescue sample size:** rescue RNA analysis had only two samples and is therefore interpreted primarily as directional/trajectory evidence.",
"3. **Restimulation interaction:** no memory kinase reached genome-wide FDR significance for the formal history-by-restimulation interaction.",
"4. **ChIP donor structure:** Day-1 and Day-6 ChIP samples are not longitudinally paired donors.",
"5. **Chromatin inference:** concordant RNA and chromatin changes do not establish causal epigenetic inheritance.",
"6. **Legacy regulatory windows:** the Step-07/07b non-promoter regions are computationally selected regions rather than experimentally validated enhancers.",
"7. **RNA re-analysis:** the RNA workflow is a downstream re-analysis of processed MMSEQ estimates and is not an exact reproduction of the original publication's differential-expression pipeline.",
"8. **RPMI Day-6 normalization:** three RPMI_d6_rep2 BigWigs were deposited as `NotNormalized`. The local audit rescales these tracks using normalized-peer genome-wide mean matching; the exact scaling factors used in the independent corrected analysis were not supplied.",
"9. **Log transformation:** the independent analysis was confirmed to use log-transformed promoter signal, but the exact transformation/pseudocount was not specified. The local implementation uses `log2(signal + 1)`.",
"10. **Numerical reproduction:** the local kinase-restricted unpaired limma model does not reproduce all independently reported corrected FDR values. In particular, the independently significant EPHB2 H3K27ac result is not reproduced locally.",
"",
"These limitations are reported explicitly so that independently corrected benchmark results are not presented as locally reproduced statistics.",
"",
"# 17. Conclusion",
"",
"This re-analysis identifies persistent and washout-associated kinase transcriptional states following LPS exposure and subsequent washout. The original RNA workflow identified 24 Day-6 kinase-family candidates and used acute response, β-glucan rescue, and restimulation behavior to provide additional trajectory context.",
"",
"The original Step-07/07b/08 chromatin workflow produced **MAP3K8, BMPR1A, and JAK3** as the strongest exploratory RNA/chromatin candidates using directional H3K27ac/H3K4me1 evidence. That ranking is retained as analysis provenance but is no longer treated as the final formal promoter-level result.",
"",
"A subsequent Day-6 promoter audit incorporated TSS ±2 kb promoter quantification, log-transformed BigWig signal, an unpaired limma design, kinase-restricted statistical testing, and explicit consideration of the three `NotNormalized` RPMI_d6_rep2 tracks.",
"",
"The local reconstruction and the independently corrected promoter results are deliberately reported separately. The exact independent FDR values were not reproduced locally.",
"",
"The independently corrected promoter review supports:",
"",
"- **JAK3:** H3K27ac FDR 0.0065 and H3K4me3 FDR 0.0141;",
"- **EPHB2:** H3K27ac FDR 0.030;",
"- **MET:** H3K27ac FDR 0.051 after normalization correction;",
"- **MAP3K8 and BMPR1A:** no significant corrected formal promoter support.",
"",
"Accordingly, the current reproducible integration workflow carries **JAK3 and EPHB2 forward for downstream external validation**.",
"",
"This should be interpreted precisely: **JAK3 + EPHB2 is the downstream integration decision obtained by combining this project's RNA evidence with the independently corrected promoter review. It is not a claim that the local chromatin limma reconstruction independently identified both genes.**",
"",
"# 18. Reproducibility",
"",
"The repository contains two related reproducible workflows.",
"",
"## Historical RNA / exploratory chromatin workflow",
"",
"Run:",
"",
"```bash",
"Rscript --vanilla run_all.R",
"```",
"",
"This executes Steps 01–08. Its original Step-08 MAP3K8/BMPR1A/JAK3 ranking is retained for provenance and should not be interpreted as the current formal promoter-supported candidate hierarchy.",
"",
"```{r historical-run-status}",
"if (!is.null(status)) {",
"  knitr::kable(",
"    status[",
"      ,",
"      intersect(",
"        c(",
'          "step",',
'          "label",',
'          "status",',
'          "elapsed_minutes",',
'          "exit_status"',
"        ),",
"        names(status)",
"      ),",
"      drop = FALSE",
"    ],",
'    caption = "Historical Steps 01-08 run status"',
"  )",
"} else {",
'  cat("`results/run_all_status.csv` was not found.")',
"}",
"```",
"",
"## Corrected Day-6 promoter audit",
"",
"Run:",
"",
"```bash",
"Rscript --vanilla run_corrected_chromatin_audit.R",
"```",
"",
"This executes the final corrected audit chain:",
"",
"```text",
"12a → 12c → 12d → 12e → 12j → 12m",
"```",
"",
"where:",
"",
"- 12a audits the Day-6 chromatin files;",
"- 12c evaluates global BigWig signal;",
"- 12d quantifies TSS ±2 kb promoter signal;",
"- 12e applies the local RPMI_d6_rep2 normalization correction;",
"- 12j performs the local kinase-restricted unpaired limma reconstruction;",
"- 12m integrates the local RNA/chromatin audit with the independently corrected promoter benchmark.",
"",
"```{r corrected-audit-status}",
"audit_status_file <-",
'  "results/12_kinase_reevaluation/12_run_status.csv"',
"",
"if (file.exists(audit_status_file)) {",
"  audit_status <- read.csv(",
"    audit_status_file,",
"    stringsAsFactors = FALSE,",
"    check.names = FALSE",
"  )",
"",
"  knitr::kable(",
"    audit_status,",
'    caption = "Corrected Day-6 chromatin audit status"',
"  )",
"} else {",
'  cat("`12_run_status.csv` was not found.")',
"}",
"```",
"",
"A successful corrected audit reports:",
"",
"```text",
"Successful steps: 6 / 6",
"Downstream priority: JAK3, EPHB2",
"```",
"",
"The final statement is an **integration result**. The independently reported Tobias FDR values remain explicitly separated from locally reproduced statistics.",
"",
"# 19. Key Output Files",
"",
"## RNA analysis",
"",
"```text",
"results/03_memory_kinases/",
"  03_memory_kinases_FDR05.csv",
"",
"results/05_integrated_trajectory/",
"  05_integrated_kinase_trajectory.csv",
"",
"figures/06_final_kinase/",
"  06D_FINAL_integrated_kinase_summary.png",
"```",
"",
"## Corrected formal chromatin audit",
"",
"```text",
"results/12_kinase_reevaluation/",
"  12_run_status.csv",
"  12a_day6_chromatin_file_manifest.csv",
"  12c_bigwig_global_qc.csv",
"  12c_RPMI_rep2_scaling_audit.csv",
"  12d_day6_sample_manifest.csv",
"  12d_target_gene_raw_promoter_signal.csv",
"  12e_RPMI_rep2_scaling_factors.csv",
"  12e_target_promoter_signal_scaling_audit.csv",
"  12j_all_kinase_corrected_limma.csv",
"  12j_target_results.csv",
"  12m_local_formal_promoter_results.csv",
"  12m_Tobias_independent_benchmark.csv",
"  12m_FINAL_candidate_status.csv",
"  12m_reproducibility_summary.csv",
"",
"figures/12_kinase_reevaluation/",
"  12m_FINAL_candidate_summary.png",
"```",
"",
"## Historical exploratory chromatin outputs",
"",
"```text",
"results/07b_unbiased_distal_chromatin/",
"  07b_corrected_gene_level_chromatin_summary.csv",
"",
"results/08_final_chromatin/",
"  08_TOP_integrated_candidates.csv",
"  08_TOP_candidate_IGV_loci_hg19.csv",
"  08_FINAL_professor_table.csv",
"",
"figures/08_final_chromatin/",
"  08A_corrected_chromatin_support_all24.png",
"  08B_HIGH_RNA_Day6_effect_with_chromatin_class.png",
"  08C_TOP_candidates_chromatin_direction.png",
"  08D_FINAL_RNA_chromatin_integration.png",
"```",
"",
"These Step-07/08 outputs are retained for provenance and exploratory interpretation; they do not determine the current formal promoter-supported downstream priority.",
"",
"# 20. Data Source",
"",
"Primary SuperSeries: **GSE85246**",
"",
"ChIP-seq subseries: **GSE85245**",
"",
"The project analyzes RNA-seq and histone ChIP-seq data from the LPS tolerance / β-glucan reprogramming study by Novakovic and colleagues.",
"",
"Chromatin analyses use hg19 GEO BigWig tracks for H3K27ac, H3K4me1, and H3K4me3. Large BigWig files are maintained locally and intentionally excluded from Git version control."
)

prefix <- if (start > 1) x[1:(start - 1)] else character(0)

writeLines(
  c(prefix, new_tail),
  file,
  useBytes = TRUE
)

cat("Sections 16-20 replaced successfully.\n")
